### ISSUE TITLE
Please add linux support.

### ISSUE THREAD

**Issue by wormeyman** [FezVrasta/brackets-darkbar#1]
I know your extension is super simple but it unfortunately does not work on linux! If you need some help I'd take a look at https://github.com/cristatus/brackets-darker which does work on linux.

**Comment by FezVrasta** [comment]
I'll see what I can do tomorrow, I've not my Linux box at home.

**Comment by FezVrasta** [comment]
I've just tested my extension on Ubuntu ad everything works correctly.

Please provide more details.

**Comment by wormeyman** [comment]
Ok i loaded up a guest session on `sprint 41 experimental build 0.41.0-13418` and the only extension i have installed is version `1.01 of Brackets dark main toolbar` and then main toolbar does not change color.

I am running elementary OS luna.

**Comment by wormeyman** [comment]
I just noticed that you have another extension called Brackets Upper Titlebar designed for linux, that one works!

**Comment by FezVrasta** [comment]
I've tried with Luna as well, tomorrow I'll try with the same build of yours.

**Comment by FezVrasta** [comment]
May you please open the developer tools (F12) and in the javascript console paste this code?

```
 $("#main-toolbar").css("background","#F00");
```

Let me know if the color of the toolbar switches to red. Thanks.

**Comment by FezVrasta** [comment]
If no response from @wormeyman I'll close this issue. Let me know.

**Comment by wormeyman** [comment]
@FezVrasta Sorry! Thanks for the reminder i forgot, that changed the color of the sidebar where the extension icons are held.

![screenshot from 2014-07-22 08 28 23](https://cloud.githubusercontent.com/assets/1795016/3660183/09cc0ea6-11b5-11e4-9255-d9b3bc8a7d5e.png)
